apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
  namespace: "sfdc"
spec:
  type: "NodePort"
  selector:
    name: "jenkins"
  ports:
    -
      name: "http"
      port: 80
      targetPort: 8080
      protocol: "TCP"
      nodePort: 30080
    -
      name: "ssh"
      port: 12222
      targetPort: 12222
      protocol: "TCP"
      nodePort: 32222
    -
      name: "slave"
      port: 50000
      protocol: "TCP"
      nodePort: 31500